### ISSUE TITLE
OWNERS and OWNERS_ALIASES should be populated with more than the bot user

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-x-plugins/jx-project#133] opened 2020-10-28 15:29 UTC
Currently these files are filed with the bot user when creating a quickstart or importing a repo.

It could be great to populate them with the dev env approvers by default, and by the one(s) passed as argument to a new parameter like "owners" for example.

**Comment by msvticket** [comment] 2023-02-10 18:22
Duplicate of #172 that has some more details

**Closed by msvticket** 2023-02-10 18:22 UTC
